Initial commit
solvedata/plugins-magento2 pull request #70
Opened 2021-06-16 03:54 UTC by liamoneill

2021-06-17 00:14 UTC, dylan-chong approved these changes
The new implementation passes all my test cases
(except for the one which we know to fail, but is a small issue)


- cart=C1, current_customer=C1 (user has had cart), reclaim, make order
    - PASS
- cart=invalid_hmac, current_customer=C1 (user has had cart), reclaim
    - PASS
- cart=C1, current_customer=null, reclaim, guest checkout as guest, make order
    - PASS
- cart=C1, current_customer=null, reclaim, sign in C1 inside checkout page, make order
    - PASS
- cart=C1, current_customer=null, reclaim, reduce quantity from C1, sign in C1
    - PASS (keeps updated quantity)
- cart=C1, current_customer=null, reclaim, remove C1's cart items from anon cart, sign in C1
    - FAIL removed items get put back into the cart on sign in
- cart=invalid_hmac, current_customer=null, reclaim
    - PASS nothing happens on reclaim
- cart=C1, current_customer=C2 (user has non-empty cart), reclaim, make order on C2 and C1 account
    - PASS
- cart=C1, C1 proceed to checkout and set address to C1's address and click Next, current_customer=C2 (user has non-empty cart), make order on C2 and C1 account
    - PASS
- cart=C1, current_customer=C3 (brand new user, no cart yet), reclaim, make order on C2 and C1 account
    - PASS

2021-06-17 02:10 UTC, liamoneill reviewed
Looks great to me.

Really like how the reclaim endpoint is getting simpler and easier to reason about the more we think about.

Just want to call out the increased risk of treating the "source" quote as authoritative over taking the maximum.

2021-06-17 02:58 UTC, dylan-chong commented on Helper/QuoteMerger.php
> +                    $mergedQty = $item->getQty();
> However it's important to note that this change means that Quote->merge is no longer commutative (which to be fair, the current implementation is only commutative with respect to the Quote's items since it does copy addresses & clobbers coupons.

It's a one way merge so it isn't technically commutative anyway

> An alternative is that we could consider only binding the QuoteInterceptor in DI for only the known usages of Quote-> merge, but I'm not sure if that's worthwhile.

It looks like it will override the functionality of the GraphQL api as well.
Another option is to instead override the assignCustomer function in app/code/Magento/Quote/Model/QuoteManagement.php which is the function that calls the merge when you login (possibly?)

there's also app/code/Magento/Checkout/Model/Session.php loadCustomerQuote() but i don't know if that's relevant to the identified+anon merge or not. looks like the merge is a hack just to get the totals. Which is possibly concerming

2021-06-17 03:02 UTC, dylan-chong commented on Plugin/Quote/QuoteInterceptor.php
> +        return $dest;
ah that was here before. i don't know if i can be bothered removing the logger only to put it back when needing to debug somethin

2021-06-17 03:04 UTC, dylan-chong requested changes
Preventing merge while thinking about the override consequences

2021-06-18 03:35 UTC, dylan-chong approved these changes
Looks great with the new `shouldUseCustomMerge` function. Would like @liamoneill to test this too

2021-06-20 09:14 UTC, liamoneill reviewed
The changes look good to me. Nice scenario testing. I've just played around with it and it worked as expected.

2021-06-20 22:03 UTC, dylan-chong commented on Plugin/Quote/QuoteInterceptor.php
> +    {
yea can rename the config option we're no longer using

2021-06-21 01:58 UTC, merged